#pragma once

// Single-file web app embedded as a C string literal
// Generated from index.html – do not edit manually, edit index.html then re-embed

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang='fr'><head><meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MotionCtrl</title>"
"<style>"
":root{--bg:#0d1117;--card:#161b22;--border:#30363d;--accent:#58a6ff;--green:#3fb950;--red:#f85149;--yellow:#e3b341;--text:#c9d1d9;--muted:#8b949e}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--text);font-family:'Segoe UI',system-ui,sans-serif;font-size:14px}"
"header{background:var(--card);border-bottom:1px solid var(--border);padding:12px 20px;display:flex;align-items:center;gap:12px}"
"header h1{font-size:18px;color:var(--accent)}#dot{width:10px;height:10px;border-radius:50%;background:var(--red);margin-left:auto}"
"#dot.ok{background:var(--green)}"
"nav{display:flex;background:var(--card);border-bottom:1px solid var(--border)}"
"nav button{flex:1;padding:10px;background:none;border:none;color:var(--muted);cursor:pointer;font-size:13px;border-bottom:2px solid transparent}"
"nav button.active{color:var(--accent);border-bottom-color:var(--accent)}"
".page{display:none;padding:16px;max-width:600px;margin:0 auto}.page.active{display:block}"
".card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:16px;margin-bottom:12px}"
".card h3{margin-bottom:12px;font-size:13px;color:var(--muted);text-transform:uppercase;letter-spacing:.5px}"
".row{display:flex;gap:8px;align-items:center;margin-bottom:8px}"
".row label{min-width:80px;color:var(--muted)}"
"input[type=text],input[type=number],select{background:#0d1117;border:1px solid var(--border);color:var(--text);border-radius:4px;padding:6px 10px;width:100%}"
".btn{border:none;border-radius:6px;padding:8px 16px;cursor:pointer;font-size:13px;font-weight:500;transition:.15s}"
".btn-primary{background:var(--accent);color:#000}"
".btn-green{background:var(--green);color:#000}"
".btn-red{background:var(--red);color:#fff}"
".btn-yellow{background:var(--yellow);color:#000}"
".btn-ghost{background:none;border:1px solid var(--border);color:var(--text)}"
".btns{display:flex;gap:8px;flex-wrap:wrap}"
".status-bar{background:var(--card);padding:10px 16px;border-bottom:1px solid var(--border);display:flex;gap:16px;font-size:12px}"
".stat{display:flex;gap:4px;align-items:center}.stat span{color:var(--muted)}"
".stat b{color:var(--accent)}"
".point-list,.seq-list{list-style:none}"
".point-list li,.seq-list li{display:flex;align-items:center;gap:8px;padding:8px;border:1px solid var(--border);border-radius:6px;margin-bottom:6px;background:#0d1117}"
".point-list li:hover,.seq-list li:hover{border-color:var(--accent)}"
".tag{background:var(--accent)22;color:var(--accent);border-radius:4px;padding:2px 6px;font-size:11px}"
".jog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;max-width:200px}"
".jog-btn{aspect-ratio:1;border:1px solid var(--border);border-radius:6px;background:var(--card);color:var(--text);font-size:18px;cursor:pointer}"
".jog-btn:active{background:var(--accent);color:#000}"
"#es-indicator{display:inline-block;padding:3px 10px;border-radius:10px;font-size:11px}"
".es-free{background:var(--green)22;color:var(--green)}"
".es-hit{background:var(--red)22;color:var(--red)}"
".curve-select{width:auto;min-width:110px}"
"</style></head>"
"<body>"
"<header><h1>⚙ MotionCtrl</h1>"
"<span id='es-indicator' class='es-free'>Endstop: free</span>"
"<div id='dot'></div></header>"
"<div class='status-bar'>"
"<div class='stat'><span>M1</span><b id='p1'>0</b>steps</div>"
"<div class='stat'><span>M2</span><b id='p2'>0</b>steps</div>"
"<div class='stat'><span>État</span><b id='state'>idle</b></div>"
"</div>"
"<nav>"
"<button class='active' onclick='tab(this,\"jog\")'>Jog</button>"
"<button onclick='tab(this,\"points\")'>Points</button>"
"<button onclick='tab(this,\"sequence\")'>Séquence</button>"
"<button onclick='tab(this,\"effects\")'>Effets</button>"
"</nav>"

// ---- JOG PAGE ----
"<div id='jog' class='page active'>"
"<div class='card'><h3>Contrôle manuel</h3>"
"<div class='row'><label>Moteur</label>"
"<select id='jog-motor'><option value='0'>Moteur 1</option><option value='1'>Moteur 2</option></select></div>"
"<div class='row'><label>Pas</label><input type='number' id='jog-steps' value='100'></div>"
"<div class='row'><label>Vitesse mm/s</label><input type='number' id='jog-speed' value='10'></div>"
"<div class='btns' style='margin-top:8px'>"
"<button class='btn btn-primary' onclick='jog(-1)'>◀ Retour</button>"
"<button class='btn btn-primary' onclick='jog(1)'>Avant ▶</button>"
"<button class='btn btn-red' onclick='send({cmd:\"STOP\"})'>■ Stop</button>"
"</div></div>"
"<div class='card'><h3>Homing</h3>"
"<div class='btns'>"
"<button class='btn btn-yellow' onclick='send({cmd:\"HOME\",motor:0})'>Home M1</button>"
"<button class='btn btn-yellow' onclick='send({cmd:\"HOME\",motor:1})'>Home M2</button>"
"<button class='btn btn-ghost' onclick='send({cmd:\"ZERO\"})'>Set zéro ici</button>"
"<button class='btn btn-ghost' onclick='send({cmd:\"ENABLE\"})'>Enable</button>"
"<button class='btn btn-ghost' onclick='send({cmd:\"DISABLE\"})'>Disable</button>"
"</div></div></div>"

// ---- POINTS PAGE ----
"<div id='points' class='page'>"
"<div class='card'><h3>Sauvegarder position</h3>"
"<div class='row'><label>Nom</label><input type='text' id='pt-name' placeholder='Point A' maxlength='31'></div>"
"<div class='btns'>"
"<button class='btn btn-green' onclick='savePoint()'>💾 Sauvegarder ici</button>"
"<button class='btn btn-ghost' onclick='loadPoints()'>↻ Rafraîchir</button>"
"</div></div>"
"<div class='card'><h3>Points sauvegardés</h3>"
"<ul class='point-list' id='point-list'></ul>"
"</div></div>"

// ---- SEQUENCE PAGE ----
"<div id='sequence' class='page'>"
"<div class='card'><h3>Ajouter un pas</h3>"
"<div class='row'><label>Point</label><select id='seq-pt'></select></div>"
"<div class='row'><label>Vitesse mm/s</label><input type='number' id='seq-speed' value='20'></div>"
"<div class='row'><label>Pause (s)</label><input type='number' id='seq-hold' value='0' step='0.1'></div>"
"<div class='row'><label>Courbe</label>"
"<select id='seq-curve' class='curve-select'>"
"<option value='0'>Linéaire</option>"
"<option value='1'>Ease In</option>"
"<option value='2'>Ease Out</option>"
"<option value='3'>Ease In/Out</option>"
"<option value='4'>Bézier</option>"
"</select></div>"
"<div class='btns'>"
"<button class='btn btn-primary' onclick='addSeqStep()'>+ Ajouter</button>"
"<button class='btn btn-ghost' onclick='loadSeq()'>↻ Rafraîchir</button>"
"<button class='btn btn-ghost' onclick='send({cmd:\"SEQ_CLEAR\"})'>🗑 Vider</button>"
"</div></div>"
"<div class='card'><h3>Séquence</h3>"
"<ul class='seq-list' id='seq-list'></ul>"
"<div class='btns' style='margin-top:10px'>"
"<button class='btn btn-green' onclick='send({cmd:\"RUN\"})'>▶ Lancer</button>"
"<button class='btn btn-yellow' onclick='send({cmd:\"PAUSE\"})'>⏸ Pause</button>"
"<button class='btn btn-ghost' onclick='send({cmd:\"RESUME\"})'>▶ Reprendre</button>"
"<button class='btn btn-red' onclick='send({cmd:\"STOP\"})'>■ Stop</button>"
"</div></div></div>"

// ---- EFFECTS PAGE ----
"<div id='effects' class='page'>"
"<div class='card'><h3>Hyperlapse</h3>"
"<div class='row'><label>Point A</label><select id='fx-a'></select></div>"
"<div class='row'><label>Point B</label><select id='fx-b'></select></div>"
"<div class='row'><label>Vitesse mm/s</label><input type='number' id='fx-speed' value='5'></div>"
"<div class='row'><label>Intervalle (s)</label><input type='number' id='fx-interval' value='1' step='0.1'></div>"
"<div class='row'><label>Nb positions</label><input type='number' id='fx-steps' value='10'></div>"
"<div class='row'><label>Répétitions</label><input type='number' id='fx-repeat' value='0' title='0=infini'></div>"
"<button class='btn btn-green' onclick='runEffect(1)'>▶ Lancer Hyperlapse</button>"
"</div>"
"<div class='card'><h3>Oscillation</h3>"
"<div class='row'><label>Point A</label><select id='osc-a'></select></div>"
"<div class='row'><label>Point B</label><select id='osc-b'></select></div>"
"<div class='row'><label>Vitesse mm/s</label><input type='number' id='osc-speed' value='15'></div>"
"<div class='row'><label>Pause (s)</label><input type='number' id='osc-interval' value='0.5' step='0.1'></div>"
"<div class='row'><label>Répétitions</label><input type='number' id='osc-repeat' value='10'></div>"
"<button class='btn btn-primary' onclick='runEffect(2)'>▶ Lancer Oscillation</button>"
"</div>"
"<div class='card'><h3>Pendulum (sinusoidal)</h3>"
"<div class='row'><label>Point A</label><select id='pen-a'></select></div>"
"<div class='row'><label>Point B</label><select id='pen-b'></select></div>"
"<div class='row'><label>Vitesse mm/s</label><input type='number' id='pen-speed' value='8'></div>"
"<div class='row'><label>Répétitions</label><input type='number' id='pen-repeat' value='5'></div>"
"<button class='btn btn-yellow' onclick='runEffect(3)'>▶ Lancer Pendulum</button>"
"</div>"
"<div class='btns'><button class='btn btn-red' onclick='send({cmd:\"STOP\"})'>■ Stop effet</button></div>"
"</div>"

// ---- JS ----
"<script>"
"let ws,points=[];"
"function connect(){"
"ws=new WebSocket('ws://'+location.hostname+'/ws');"
"ws.onopen=()=>{ document.getElementById('dot').className='ok'; loadPoints(); loadSeq(); };"
"ws.onclose=()=>{ document.getElementById('dot').className=''; setTimeout(connect,2000); };"
"ws.onmessage=e=>{ let d=JSON.parse(e.data); handleMsg(d); };"
"}"
"function handleMsg(d){"
"if(d.type==='status'){"
"document.getElementById('p1').textContent=d.m1_pos;"
"document.getElementById('p2').textContent=d.m2_pos;"
"document.getElementById('state').textContent=d.state;"
"let es=document.getElementById('es-indicator');"
"if(d.endstop){es.textContent='Endstop: ⚡ déclenché';es.className='es-hit';}"
"else{es.textContent='Endstop: libre';es.className='es-free';}"
"}else if(d.type==='points'){renderPoints(d.data);}"
"else if(d.type==='sequence'){renderSeq(d.data);}"
"}"
"function send(obj){ if(ws&&ws.readyState===1)ws.send(JSON.stringify(obj)); }"
"function tab(btn,id){"
"document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));"
"btn.classList.add('active');"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.getElementById(id).classList.add('active');"
"}"
"function jog(dir){"
"let m=+document.getElementById('jog-motor').value;"
"let s=+document.getElementById('jog-steps').value;"
"let sp=+document.getElementById('jog-speed').value;"
"send({cmd:'JOG',motor:m,steps:s*dir,speed:sp});"
"}"
"function savePoint(){"
"let n=document.getElementById('pt-name').value.trim();"
"if(!n){alert('Nom requis');return;}"
"send({cmd:'SAVE_POINT',name:n});"
"setTimeout(loadPoints,300);"
"}"
"function loadPoints(){ send({cmd:'GET_POINTS'}); }"
"function loadSeq(){ send({cmd:'GET_SEQ'}); }"
"function renderPoints(arr){"
"points=arr||[];"
"let ul=document.getElementById('point-list');"
"ul.innerHTML='';"
"let selects=['seq-pt','fx-a','fx-b','osc-a','osc-b','pen-a','pen-b'];"
"selects.forEach(id=>{ let s=document.getElementById(id); if(s) s.innerHTML=''; });"
"points.forEach(p=>{"
"let li=document.createElement('li');"
"li.innerHTML='<span class=\"tag\">#'+p.idx+'</span><b style=\"flex:1\">'+p.name+'</b>'+"
"'<small style=\"color:var(--muted)\">M1:'+p.m1+' M2:'+p.m2+'</small>'+"
"'<button class=\"btn btn-primary\" style=\"padding:4px 8px\" onclick=\"gotoPoint('+p.idx+')\">Aller</button>'+"
"'<button class=\"btn btn-red\" style=\"padding:4px 8px\" onclick=\"delPoint('+p.idx+')\">✕</button>';"
"ul.appendChild(li);"
"selects.forEach(id=>{"
"let s=document.getElementById(id);"
"if(s){let o=document.createElement('option');o.value=p.idx;o.textContent=p.name;s.appendChild(o);}"
"});"
"});"
"}"
"function gotoPoint(idx){"
"let sp=prompt('Vitesse mm/s?','15');"
"if(sp)send({cmd:'GOTO',idx:idx,speed:parseFloat(sp)});"
"}"
"function delPoint(idx){ if(confirm('Supprimer ce point?'))send({cmd:'DEL_POINT',idx:idx}); setTimeout(loadPoints,300); }"
"function renderSeq(arr){"
"let ul=document.getElementById('seq-list');"
"ul.innerHTML='';"
"let curves=['Linéaire','Ease In','Ease Out','Ease I/O','Bézier'];"
"(arr||[]).forEach((s,i)=>{"
"let name=(points.find(p=>p.idx===s.point)||{}).name||'P'+s.point;"
"let li=document.createElement('li');"
"li.innerHTML='<span class=\"tag\">'+i+'</span><b style=\"flex:1\">'+name+'</b>'+"
"'<small style=\"color:var(--muted)\">'+s.speed+'mm/s '+curves[s.curve]+(s.hold?'+'+s.hold+'s':'')+'</small>'+"
"'<button class=\"btn btn-ghost\" style=\"padding:4px 8px\" onclick=\"delStep('+i+')\">✕</button>';"
"ul.appendChild(li);"
"});"
"}"
"function addSeqStep(){"
"let pt=document.getElementById('seq-pt').value;"
"if(pt===''){alert('Sélectionnez un point');return;}"
"send({cmd:'SEQ_ADD',point:+pt,"
"speed:+document.getElementById('seq-speed').value,"
"hold:+document.getElementById('seq-hold').value,"
"curve:+document.getElementById('seq-curve').value});"
"setTimeout(loadSeq,300);"
"}"
"function delStep(idx){ send({cmd:'SEQ_DEL',idx:idx}); setTimeout(loadSeq,300); }"
"function runEffect(type){"
"let cfg={cmd:'EFFECT',effect_type:type};"
"if(type===1){"
"cfg.point_a=+document.getElementById('fx-a').value;"
"cfg.point_b=+document.getElementById('fx-b').value;"
"cfg.speed=+document.getElementById('fx-speed').value;"
"cfg.interval=+document.getElementById('fx-interval').value;"
"cfg.param1=+document.getElementById('fx-steps').value;"
"cfg.repeat=+document.getElementById('fx-repeat').value;"
"}else if(type===2){"
"cfg.point_a=+document.getElementById('osc-a').value;"
"cfg.point_b=+document.getElementById('osc-b').value;"
"cfg.speed=+document.getElementById('osc-speed').value;"
"cfg.interval=+document.getElementById('osc-interval').value;"
"cfg.repeat=+document.getElementById('osc-repeat').value;"
"}else if(type===3){"
"cfg.point_a=+document.getElementById('pen-a').value;"
"cfg.point_b=+document.getElementById('pen-b').value;"
"cfg.speed=+document.getElementById('pen-speed').value;"
"cfg.repeat=+document.getElementById('pen-repeat').value;"
"}"
"send(cfg);"
"}"
"connect();"
"</script></body></html>";
